apiVersion: v1
kind: Service
metadata:
  name: addressbook-loadbalancer
  labels:
    service: addressbook-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 31444
    protocol: TCP
  selector:
    app: addressbook               
