apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels: 
    service: my-service
spec:
 type: NodePort
 selector:
    app: my-app
 ports:
  - name: http
    protocol: TCP
    port: 80
    nodePort: 32222
