apiVersion: v1
kind: Service
metadata:
  name: my-service-loadbalancer
  labels: 
    service: my-service-loadbalancer
spec:
 type: LoadBalancer
 selector:
    app: my-app
 ports:
  - name: http
    protocol: TCP
    port: 80
    nodePort: 31222
